# Generated by Django 4.0 on 2021-12-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя героя')),
                ('strength', models.CharField(max_length=5)),
                ('agility', models.CharField(max_length=5)),
                ('intellect', models.CharField(max_length=5)),
                ('strengthplus', models.CharField(max_length=5)),
                ('agilityplus', models.CharField(max_length=5)),
                ('intellectplus', models.CharField(max_length=5)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Otz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тема отзыва')),
                ('task', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
