# Generated by Django 4.0 on 2022-01-18 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conter',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.heroe')),
                ('good1', models.ImageField(upload_to='photos/')),
                ('good2', models.ImageField(upload_to='photos/')),
                ('good3', models.ImageField(upload_to='photos/')),
                ('bad1', models.ImageField(upload_to='photos/')),
                ('bad2', models.ImageField(upload_to='photos/')),
                ('bad3', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
