# Generated by Django 4.0 on 2022-01-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_conter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conter',
            old_name='name',
            new_name='heroe',
        ),
    ]
