# Generated by Django 4.0 on 2022-01-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0003_rename_name_conter_heroe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sborki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание сборки')),
                ('photo', models.ImageField(upload_to='photos/Sborki', verbose_name='Сборка')),
                ('heroe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.heroe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
