# Generated by Django 4.0 on 2022-01-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_otzivi_delete_otziv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sborki',
            name='photo',
        ),
    ]
