# Generated by Django 4.0 on 2022-01-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_sborki_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otzivi',
        ),
    ]
